name: SonarCloud SAST

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  NODE_DEFAULT_VERSION: 20
  ANGULAR_CLI_VERSION: 17

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Setup Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_DEFAULT_VERSION }} # Ensure it matches your application's version
        cache: npm

    # Install minimalistically
    - name: Install application minimalistically
      run: npm install --ignore-scripts

    # Build the project (if necessary)
    - name: Build the project
      run: npm run build

    # SonarCloud Scan
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v2
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=dimdimuzun
          -Dsonar.projectKey=dimdimuzun_juice-shop-github-actions