name: SonarCloud Scan

on:
  push:
    branches:
      - main           # Запуск на пуш у гілку main
  pull_request:
    branches:
      - "*"            # Запуск на всі пул-реквести

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'       # Вказуємо версію Node.js (під джузи шоп)

      - name: Install dependencies
        run: npm install           # Встановлюємо залежності через npm

      - name: Run SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          projectKey: <juice-shop-github-actions>
          organization: <van-lefiren>
          token: ${{ secrets.SONAR_TOKEN }}
