name: ZAP Scan as DAST with GitHub Actions

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
permissions:
  issues: write
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      issues: write
    name: Scan the web applications
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.13.0
        with:
          docker_name: 'zaproxy/zap-stable'
          target: 'https://demo.owasp-juice.shop'
          cmd_options: '-a'
